### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by hjelmj** [hjelmj/planets#1]
This is a test issue for teaching using the planets repo

@DorisHoffmeyer

@MathiasKchristensen

Markdown

###  title

*italics*

**bold**

**Comment by hjelmj** [comment]
more comments please :-)

**Comment by DorisHoffmeyer** [comment]
All the comments

**Comment by MathiasKchristensen** [comment]
Much obliged

**Comment by hjelmj** [comment]
OK, thanks, closing issue!
